// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdtr8WZW86Q3YRxVxQ7yEMFQ6r1eyngDs',
    appId: '1:878292741711:web:21c7729c614c6e1590443a',
    messagingSenderId: '878292741711',
    projectId: 'pupbili-database',
    authDomain: 'pupbili-database.firebaseapp.com',
    storageBucket: 'pupbili-database.firebasestorage.app',
    measurementId: 'G-J9EMDLF27J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxqyMMtdkI-tPPGy076tn09wzFo4uS0w4',
    appId: '1:878292741711:android:2fc0b3d3e67ef41490443a',
    messagingSenderId: '878292741711',
    projectId: 'pupbili-database',
    storageBucket: 'pupbili-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpY7QNFb3ZHzCG_9U5DdwHzpt149QO-pI',
    appId: '1:878292741711:ios:1c1551d19305289690443a',
    messagingSenderId: '878292741711',
    projectId: 'pupbili-database',
    storageBucket: 'pupbili-database.firebasestorage.app',
    iosBundleId: 'com.example.projectmanaPupbili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpY7QNFb3ZHzCG_9U5DdwHzpt149QO-pI',
    appId: '1:878292741711:ios:1c1551d19305289690443a',
    messagingSenderId: '878292741711',
    projectId: 'pupbili-database',
    storageBucket: 'pupbili-database.firebasestorage.app',
    iosBundleId: 'com.example.projectmanaPupbili',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdtr8WZW86Q3YRxVxQ7yEMFQ6r1eyngDs',
    appId: '1:878292741711:web:4e08d75942bfdfea90443a',
    messagingSenderId: '878292741711',
    projectId: 'pupbili-database',
    authDomain: 'pupbili-database.firebaseapp.com',
    storageBucket: 'pupbili-database.firebasestorage.app',
    measurementId: 'G-K2T0CN3167',
  );
}
